# Generated by Django 2.1.4 on 2019-02-04 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190204_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='match_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='webapp.Item'),
        ),
    ]
