# Generated by Django 2.1.4 on 2019-02-04 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190204_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='match_item',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='match', to='webapp.Item'),
        ),
    ]
