# Generated by Django 2.1.4 on 2019-02-12 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0008_auto_20190204_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500)),
                ('sent_at', models.DateTimeField()),
                ('item_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_messages', to='webapp.Item')),
                ('item_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='webapp.Item')),
                ('user_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_messages', to=settings.AUTH_USER_MODEL)),
                ('user_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
